// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\profiles\{profileId}\kyc-reviews
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KycReviewsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wise.OpenApiClient.v2.profiles.item.kycReviews.item collection</summary>
        /// <param name="position">The KYC Review ID.</param>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder"/></returns>
        public global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder this[Guid position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("kycReviewId", position);
                return new global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the Soenneker.Wise.OpenApiClient.v2.profiles.item.kycReviews.item collection</summary>
        /// <param name="position">The KYC Review ID.</param>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("kycReviewId", position);
                return new global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.Item.WithKycReviewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.KycReviewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KycReviewsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/profiles/{profileId}/kyc-reviews", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.KycReviews.KycReviewsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KycReviewsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/profiles/{profileId}/kyc-reviews", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
