// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions.Import;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\simulation\profiles\{profileId}\bank-transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BankTransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The import property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions.Import.ImportRequestBuilder Import
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions.Import.ImportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions.BankTransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankTransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/simulation/profiles/{profileId}/bank-transactions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Simulation.Profiles.Item.BankTransactions.BankTransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BankTransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/simulation/profiles/{profileId}/bank-transactions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
