// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Spend.Applications.Item.SpendControls.Rules
{
    /// <summary>Determines whether the transactions should be allowed or blocked.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RulesPostRequestBody_operation
    {
        [EnumMember(Value = "ALLOW")]
        #pragma warning disable CS1591
        ALLOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "BLOCK")]
        #pragma warning disable CS1591
        BLOCK,
        #pragma warning restore CS1591
    }
}
