// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Spend.Profiles.Item.CardOrders
{
    /// <summary>Reason for replacing the card:- `CARD_DAMAGED`- `CARD_EXPIRING`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardOrdersPostRequestBody_replacementDetails_reason
    {
        [EnumMember(Value = "CARD_DAMAGED")]
        #pragma warning disable CS1591
        CARD_DAMAGED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CARD_EXPIRING")]
        #pragma warning disable CS1591
        CARD_EXPIRING,
        #pragma warning restore CS1591
    }
}
