// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Reversal
{
    [Obsolete("This class is obsolete. Use ReversalPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ReversalResponse : global::Soenneker.Wise.OpenApiClient.V1.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Reversal.ReversalPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Reversal.ReversalResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Wise.OpenApiClient.V1.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Reversal.ReversalResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Reversal.ReversalResponse();
        }
    }
}
#pragma warning restore CS0618
