// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.DirectDebitAccounts
{
    /// <summary>Bank account type.- `CHECKING` — Checking account (USD, CAD)- `SAVINGS` — Savings account (USD, CAD)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DirectDebitAccountsPostRequestBody_details_accountType
    {
        [EnumMember(Value = "CHECKING")]
        #pragma warning disable CS1591
        CHECKING,
        #pragma warning restore CS1591
        [EnumMember(Value = "SAVINGS")]
        #pragma warning disable CS1591
        SAVINGS,
        #pragma warning restore CS1591
    }
}
