// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V1.User.ClaimAccount;
using Soenneker.Wise.OpenApiClient.V1.User.Facemap;
using Soenneker.Wise.OpenApiClient.V1.User.PartnerDeviceFingerprints;
using Soenneker.Wise.OpenApiClient.V1.User.Pin;
using Soenneker.Wise.OpenApiClient.V1.User.Signup;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.User
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The claimAccount property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.ClaimAccount.ClaimAccountRequestBuilder ClaimAccount
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.ClaimAccount.ClaimAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The facemap property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.Facemap.FacemapRequestBuilder Facemap
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.Facemap.FacemapRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The partnerDeviceFingerprints property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.PartnerDeviceFingerprints.PartnerDeviceFingerprintsRequestBuilder PartnerDeviceFingerprints
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.PartnerDeviceFingerprints.PartnerDeviceFingerprintsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pin property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.Pin.PinRequestBuilder Pin
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.Pin.PinRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The signup property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.Signup.SignupRequestBuilder Signup
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.Signup.SignupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/user", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/user", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
