// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Profiles.Item.BusinessProfile
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BusinessProfilePutRequestBody_address : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>First line of address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressFirstLine { get; set; }
#nullable restore
#else
        public string AddressFirstLine { get; set; }
#endif
        /// <summary>City.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>2 letter country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryIso2Code { get; set; }
#nullable restore
#else
        public string CountryIso2Code { get; set; }
#endif
        /// <summary>3 letter country code. Must be lowercase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryIso3Code { get; set; }
#nullable restore
#else
        public string CountryIso3Code { get; set; }
#endif
        /// <summary>Postal code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostCode { get; set; }
#nullable restore
#else
        public string PostCode { get; set; }
#endif
        /// <summary>State code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StateCode { get; set; }
#nullable restore
#else
        public string StateCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.BusinessProfile.BusinessProfilePutRequestBody_address"/> and sets the default values.
        /// </summary>
        public BusinessProfilePutRequestBody_address()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.BusinessProfile.BusinessProfilePutRequestBody_address"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.BusinessProfile.BusinessProfilePutRequestBody_address CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V2.Profiles.Item.BusinessProfile.BusinessProfilePutRequestBody_address();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "addressFirstLine", n => { AddressFirstLine = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "countryIso2Code", n => { CountryIso2Code = n.GetStringValue(); } },
                { "countryIso3Code", n => { CountryIso3Code = n.GetStringValue(); } },
                { "postCode", n => { PostCode = n.GetStringValue(); } },
                { "stateCode", n => { StateCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("addressFirstLine", AddressFirstLine);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("countryIso2Code", CountryIso2Code);
            writer.WriteStringValue("countryIso3Code", CountryIso3Code);
            writer.WriteStringValue("postCode", PostCode);
            writer.WriteStringValue("stateCode", StateCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
