// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Spend.Profiles.Item.CardOrders.Availability
{
    /// <summary>The type of the card:- `VIRTUAL_NON_UPGRADEABLE`- `PHYSICAL`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AvailabilityGetResponse_cardPrograms_cardType
    {
        [EnumMember(Value = "VIRTUAL_NON_UPGRADEABLE")]
        #pragma warning disable CS1591
        VIRTUAL_NON_UPGRADEABLE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PHYSICAL")]
        #pragma warning disable CS1591
        PHYSICAL,
        #pragma warning restore CS1591
    }
}
