// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\profiles\{profileId}\transfers\{transferId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTransferItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The payments property</summary>
        public global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.WithTransferItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTransferItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/profiles/{profileId}/transfers/{transferId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.WithTransferItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTransferItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/profiles/{profileId}/transfers/{transferId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
