// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Profiles.Item.AccountDetailsOrders
{
    /// <summary>Order status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AccountDetailsOrders_status
    {
        [EnumMember(Value = "PENDING_USER")]
        #pragma warning disable CS1591
        PENDING_USER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING_TW")]
        #pragma warning disable CS1591
        PENDING_TW,
        #pragma warning restore CS1591
        [EnumMember(Value = "REQUIREMENTS_FULFILLED")]
        #pragma warning disable CS1591
        REQUIREMENTS_FULFILLED,
        #pragma warning restore CS1591
        [EnumMember(Value = "DONE")]
        #pragma warning disable CS1591
        DONE,
        #pragma warning restore CS1591
    }
}
