// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.Details
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DetailsPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Name on the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardholderName { get; set; }
#nullable restore
#else
        public string CardholderName { get; set; }
#endif
        /// <summary>The card CVV2 security code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cvv2 { get; set; }
#nullable restore
#else
        public string Cvv2 { get; set; }
#endif
        /// <summary>The card expiry date in MM/YY format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiryDate { get; set; }
#nullable restore
#else
        public string ExpiryDate { get; set; }
#endif
        /// <summary>An arbitrary UUID issued from the cryptographic communication.</summary>
        public Guid? Nonce { get; set; }
        /// <summary>The card Primary Account Number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pan { get; set; }
#nullable restore
#else
        public string Pan { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.Details.DetailsPostResponse"/> and sets the default values.
        /// </summary>
        public DetailsPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.Details.DetailsPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.Details.DetailsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.Details.DetailsPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cardholderName", n => { CardholderName = n.GetStringValue(); } },
                { "cvv2", n => { Cvv2 = n.GetStringValue(); } },
                { "expiryDate", n => { ExpiryDate = n.GetStringValue(); } },
                { "nonce", n => { Nonce = n.GetGuidValue(); } },
                { "pan", n => { Pan = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cardholderName", CardholderName);
            writer.WriteStringValue("cvv2", Cvv2);
            writer.WriteStringValue("expiryDate", ExpiryDate);
            writer.WriteGuidValue("nonce", Nonce);
            writer.WriteStringValue("pan", Pan);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
