// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V4.Profiles.Item.Balances;
using Soenneker.Wise.OpenApiClient.V4.Profiles.Item.MultiCurrencyAccount;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V4.Profiles.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v4\profiles\{profileId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProfileItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The balances property</summary>
        public global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.Balances.BalancesRequestBuilder Balances
        {
            get => new global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.Balances.BalancesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The multiCurrencyAccount property</summary>
        public global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.MultiCurrencyAccount.MultiCurrencyAccountRequestBuilder MultiCurrencyAccount
        {
            get => new global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.MultiCurrencyAccount.MultiCurrencyAccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.WithProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProfileItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v4/profiles/{profileId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V4.Profiles.Item.WithProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProfileItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v4/profiles/{profileId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
