// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption;
using Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning;
using Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.TwcardData.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \twcard-data\v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The clientSideEncryption property</summary>
        public global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.ClientSideEncryptionRequestBuilder ClientSideEncryption
        {
            get => new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.ClientSideEncryptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The pushProvisioning property</summary>
        public global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.PushProvisioningRequestBuilder PushProvisioning
        {
            get => new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.PushProvisioningRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sensitiveCardData property</summary>
        public global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.SensitiveCardDataRequestBuilder SensitiveCardData
        {
            get => new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.SensitiveCardData.SensitiveCardDataRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
