// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Auth.Jose.Response.PublicKeys
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAlgorithmQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ES256")]
        #pragma warning disable CS1591
        ES256,
        #pragma warning restore CS1591
        [EnumMember(Value = "ES384")]
        #pragma warning disable CS1591
        ES384,
        #pragma warning restore CS1591
        [EnumMember(Value = "ES512")]
        #pragma warning disable CS1591
        ES512,
        #pragma warning restore CS1591
        [EnumMember(Value = "PS256")]
        #pragma warning disable CS1591
        PS256,
        #pragma warning restore CS1591
        [EnumMember(Value = "PS384")]
        #pragma warning disable CS1591
        PS384,
        #pragma warning restore CS1591
        [EnumMember(Value = "PS512")]
        #pragma warning disable CS1591
        PS512,
        #pragma warning restore CS1591
        [EnumMember(Value = "RSA_OAEP_256")]
        #pragma warning disable CS1591
        RSA_OAEP_256,
        #pragma warning restore CS1591
    }
}
