// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Auth.Jose.Response.PublicKeys
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetScopeQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "PAYLOAD_SIGNING")]
        #pragma warning disable CS1591
        PAYLOAD_SIGNING,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYLOAD_ENCRYPTION")]
        #pragma warning disable CS1591
        PAYLOAD_ENCRYPTION,
        #pragma warning restore CS1591
    }
}
