// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Transfers.Item.Invoices.Bankingpartner
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BankingpartnerGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name of the sending bank to the recipient&apos;s bank</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankingPartnerName { get; set; }
#nullable restore
#else
        public string BankingPartnerName { get; set; }
#endif
        /// <summary>The reference used by the partner bank to identify and track the transfer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankingPartnerReference { get; set; }
#nullable restore
#else
        public string BankingPartnerReference { get; set; }
#endif
        /// <summary>The delivery mode for the payment (e.g. SWIFT)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeliveryMode { get; set; }
#nullable restore
#else
        public string DeliveryMode { get; set; }
#endif
        /// <summary>The MT103 of the transfer, if available</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mt103 { get; set; }
#nullable restore
#else
        public string Mt103 { get; set; }
#endif
        /// <summary>The legal entity that processed the transfer on behalf of the customer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProcessorName { get; set; }
#nullable restore
#else
        public string ProcessorName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Transfers.Item.Invoices.Bankingpartner.BankingpartnerGetResponse"/> and sets the default values.
        /// </summary>
        public BankingpartnerGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V2.Transfers.Item.Invoices.Bankingpartner.BankingpartnerGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V2.Transfers.Item.Invoices.Bankingpartner.BankingpartnerGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V2.Transfers.Item.Invoices.Bankingpartner.BankingpartnerGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankingPartnerName", n => { BankingPartnerName = n.GetStringValue(); } },
                { "bankingPartnerReference", n => { BankingPartnerReference = n.GetStringValue(); } },
                { "deliveryMode", n => { DeliveryMode = n.GetStringValue(); } },
                { "mt103", n => { Mt103 = n.GetStringValue(); } },
                { "processorName", n => { ProcessorName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bankingPartnerName", BankingPartnerName);
            writer.WriteStringValue("bankingPartnerReference", BankingPartnerReference);
            writer.WriteStringValue("deliveryMode", DeliveryMode);
            writer.WriteStringValue("mt103", Mt103);
            writer.WriteStringValue("processorName", ProcessorName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
