// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Transfers.Item.DepositDetails.BankTransfer
{
    /// <summary>
    /// Account detail entry.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BankTransferGetResponse_payinBankAccount_details : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Description of the account detail type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Account details value, formatted according to the type of the field. Intended to be human-readable. This can be null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormattedValue { get; set; }
#nullable restore
#else
        public string FormattedValue { get; set; }
#endif
        /// <summary>Account details label that should be displayed in your user interface.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Account details value, always unformatted. Can be used for processing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RawValue { get; set; }
#nullable restore
#else
        public string RawValue { get; set; }
#endif
        /// <summary>Account details type, e.g. accountNumber, iban etc.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>Account details value. This field is deprecated. Use `rawValue` and `formattedValue` instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Transfers.Item.DepositDetails.BankTransfer.BankTransferGetResponse_payinBankAccount_details"/> and sets the default values.
        /// </summary>
        public BankTransferGetResponse_payinBankAccount_details()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Transfers.Item.DepositDetails.BankTransfer.BankTransferGetResponse_payinBankAccount_details"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Transfers.Item.DepositDetails.BankTransfer.BankTransferGetResponse_payinBankAccount_details CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Transfers.Item.DepositDetails.BankTransfer.BankTransferGetResponse_payinBankAccount_details();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "formattedValue", n => { FormattedValue = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "rawValue", n => { RawValue = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("formattedValue", FormattedValue);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("rawValue", RawValue);
            writer.WriteStringValue("type", Type);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
