// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\profiles\{profileId}\balances\hold-limit-breach\{holdLimitBreachId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithHoldLimitBreachItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithHoldLimitBreachItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/profiles/{profileId}/balances/hold-limit-breach/{holdLimitBreachId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithHoldLimitBreachItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/profiles/{profileId}/balances/hold-limit-breach/{holdLimitBreachId}", rawUrl)
        {
        }
        /// <summary>
        /// Closes an open hold limit breach by performing a one-time refund to a specified recipient. The recipient will receive the excess amount that caused the breach.Only breaches with `state: OPEN` can be closed via this endpoint.
        /// </summary>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.WithHoldLimitBreach429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach400Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreach404Error.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Wise.OpenApiClient.Models.WithHoldLimitBreach429Error.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Closes an open hold limit breach by performing a one-time refund to a specified recipient. The recipient will receive the excess amount that caused the breach.Only breaches with `state: OPEN` can be closed via this endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.Balances.HoldLimitBreach.Item.WithHoldLimitBreachItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
