// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Profiles.Item.BatchPayments.Item.Payments
{
    /// <summary>Current batch group status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentsPostResponse_status
    {
        [EnumMember(Value = "NEW")]
        #pragma warning disable CS1591
        NEW,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "MARKED_FOR_CANCELLATION")]
        #pragma warning disable CS1591
        MARKED_FOR_CANCELLATION,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING_CANCEL")]
        #pragma warning disable CS1591
        PROCESSING_CANCEL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
    }
}
