// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Profiles.Item.BatchPayments.Item.Payments
{
    /// <summary>The method of payment to use.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaymentsPostRequestBody_type
    {
        [EnumMember(Value = "BALANCE")]
        #pragma warning disable CS1591
        BALANCE,
        #pragma warning restore CS1591
    }
}
