// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.ExcessMoneyAccount
{
    /// <summary>
    /// Response from configuring an excess money account.
    /// </summary>
    [Obsolete("This class is obsolete. Use ExcessMoneyAccountPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ExcessMoneyAccountResponse : global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.ExcessMoneyAccount.ExcessMoneyAccountPostResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.ExcessMoneyAccount.ExcessMoneyAccountResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.ExcessMoneyAccount.ExcessMoneyAccountResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.ExcessMoneyAccount.ExcessMoneyAccountResponse();
        }
    }
}
#pragma warning restore CS0618
