// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.FetchEncryptingKey;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption
{
    /// <summary>
    /// Builds and executes requests for operations under \twcard-data\v1\clientSideEncryption
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientSideEncryptionRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The fetchEncryptingKey property</summary>
        public global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.FetchEncryptingKey.FetchEncryptingKeyRequestBuilder FetchEncryptingKey
        {
            get => new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.FetchEncryptingKey.FetchEncryptingKeyRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.ClientSideEncryptionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientSideEncryptionRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1/clientSideEncryption", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.ClientSideEncryption.ClientSideEncryptionRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientSideEncryptionRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1/clientSideEncryption", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
