// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item.SpendLimits;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \spend\profiles\{businessProfile-id}\card-holder-profiles\{cardHolderProfileId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithCardHolderProfileItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The spendLimits property</summary>
        public global::Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item.SpendLimits.SpendLimitsRequestBuilder SpendLimits
        {
            get => new global::Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item.SpendLimits.SpendLimitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item.WithCardHolderProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCardHolderProfileItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/spend/profiles/{businessProfile%2Did}/card-holder-profiles/{cardHolderProfileId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Spend.Profiles.Item.CardHolderProfiles.Item.WithCardHolderProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithCardHolderProfileItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/spend/profiles/{businessProfile%2Did}/card-holder-profiles/{cardHolderProfileId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
