// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Models;
using Soenneker.Wise.OpenApiClient.Quotes.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.Quotes
{
    /// <summary>
    /// Builds and executes requests for operations under \quotes
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QuotesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Wise.OpenApiClient.quotes.item collection</summary>
        /// <param name="position">Quote ID (supports long or UUID based IDs).</param>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Quotes.Item.WithQuoteItemRequestBuilder"/></returns>
        public global::Soenneker.Wise.OpenApiClient.Quotes.Item.WithQuoteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("quoteId", position);
                return new global::Soenneker.Wise.OpenApiClient.Quotes.Item.WithQuoteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Quotes.QuotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/quotes", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Quotes.QuotesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QuotesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/quotes", rawUrl)
        {
        }
        /// <summary>
        /// Use this endpoint to get example quotes for illustrative purposes. This allows you to show the exchange rate and fees Wise offers before a user has created or linked an account. Often used to display a quote screen showing your customers what Wise offers before they sign up.Note that this endpoint does not require a token to create the resource. However, since it is just an example, the returned quote has no ID and can&apos;t be used to create a transfer.To get quotes with an accurate partner fee, include the Authorization header in the request with your client credentials token. Otherwise, you do not need to include the Authorization header.{% admonition type=&quot;info&quot; %}Unauthenticated quotes cannot be used to create transfers. They are meant for illustration purposes in partner interfaces only. When creating a transfer, be sure to use an authenticated quote.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.Quote"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Value429ResponseContent">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wise.OpenApiClient.Models.Quote?> PostAsync(global::Soenneker.Wise.OpenApiClient.Models.QuoteCreateUnauthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wise.OpenApiClient.Models.Quote> PostAsync(global::Soenneker.Wise.OpenApiClient.Models.QuoteCreateUnauthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Wise.OpenApiClient.Models.Value429ResponseContent.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Wise.OpenApiClient.Models.Quote>(requestInfo, global::Soenneker.Wise.OpenApiClient.Models.Quote.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Use this endpoint to get example quotes for illustrative purposes. This allows you to show the exchange rate and fees Wise offers before a user has created or linked an account. Often used to display a quote screen showing your customers what Wise offers before they sign up.Note that this endpoint does not require a token to create the resource. However, since it is just an example, the returned quote has no ID and can&apos;t be used to create a transfer.To get quotes with an accurate partner fee, include the Authorization header in the request with your client credentials token. Otherwise, you do not need to include the Authorization header.{% admonition type=&quot;info&quot; %}Unauthenticated quotes cannot be used to create transfers. They are meant for illustration purposes in partner interfaces only. When creating a transfer, be sure to use an authenticated quote.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.Models.QuoteCreateUnauthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.Models.QuoteCreateUnauthenticatedRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Quotes.QuotesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.Quotes.QuotesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.Quotes.QuotesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
