// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Authorisation;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\simulation\spend\profiles\{profileId}\cards\{cardToken}\transactions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransactionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The authorisation property</summary>
        public global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Authorisation.AuthorisationRequestBuilder Authorisation
        {
            get => new global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Authorisation.AuthorisationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/simulation/spend/profiles/{profileId}/cards/{cardToken}/transactions{?limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TransactionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/simulation/spend/profiles/{profileId}/cards/{cardToken}/transactions{?limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of simulated card transactions, in descending order of creation time.To retrieve more details of a transaction, use the [get card transaction by ID](/api-reference/card-transaction/cardtransactionget) endpoint.
        /// </summary>
        /// <returns>A List&lt;global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Transactions&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Transactions>?> GetAsync(Action<RequestConfiguration<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Transactions>> GetAsync(Action<RequestConfiguration<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Transactions>(requestInfo, global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.Transactions.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Returns a list of simulated card transactions, in descending order of creation time.To retrieve more details of a transaction, use the [get card transaction by ID](/api-reference/card-transaction/cardtransactionget) endpoint.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder.TransactionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.V2.Simulation.Spend.Profiles.Item.Cards.Item.Transactions.TransactionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of simulated card transactions, in descending order of creation time.To retrieve more details of a transaction, use the [get card transaction by ID](/api-reference/card-transaction/cardtransactionget) endpoint.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TransactionsRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of transactions to return. The default value is 10.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
    }
}
#pragma warning restore CS0618
