// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.PartnerLicenceTransfers
{
    /// <summary>
    /// Originator name details. Required fields depend on the legal entity type: `givenName` and `familyName` are required for `PRIVATE`, `fullName` is required for `BUSINESS`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PartnerLicenceTransfersPostRequestBody_originator_name : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Payment originator family name. Required if `legalEntityType = PRIVATE`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FamilyName { get; set; }
#nullable restore
#else
        public string FamilyName { get; set; }
#endif
        /// <summary>Payment originator full legal name. Required if `legalEntityType = BUSINESS`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>Payment originator first name. Required if `legalEntityType = PRIVATE`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GivenName { get; set; }
#nullable restore
#else
        public string GivenName { get; set; }
#endif
        /// <summary>Payment originator middle name(s). Used only if `legalEntityType = PRIVATE`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MiddleNames { get; set; }
#nullable restore
#else
        public List<string> MiddleNames { get; set; }
#endif
        /// <summary>Payment originator patronymic name. Used only if `legalEntityType = PRIVATE`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PatronymicName { get; set; }
#nullable restore
#else
        public string PatronymicName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.PartnerLicenceTransfers.PartnerLicenceTransfersPostRequestBody_originator_name"/> and sets the default values.
        /// </summary>
        public PartnerLicenceTransfersPostRequestBody_originator_name()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.PartnerLicenceTransfers.PartnerLicenceTransfersPostRequestBody_originator_name"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.PartnerLicenceTransfers.PartnerLicenceTransfersPostRequestBody_originator_name CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Profiles.Item.PartnerLicenceTransfers.PartnerLicenceTransfersPostRequestBody_originator_name();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "familyName", n => { FamilyName = n.GetStringValue(); } },
                { "fullName", n => { FullName = n.GetStringValue(); } },
                { "givenName", n => { GivenName = n.GetStringValue(); } },
                { "middleNames", n => { MiddleNames = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "patronymicName", n => { PatronymicName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("familyName", FamilyName);
            writer.WriteStringValue("fullName", FullName);
            writer.WriteStringValue("givenName", GivenName);
            writer.WriteCollectionOfPrimitiveValues<string>("middleNames", MiddleNames);
            writer.WriteStringValue("patronymicName", PatronymicName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
