// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles.Item.KycReviews
{
    /// <summary>Type of the underlying action or process this KYC Review is for. Usually a reference to which product this KYC Review is for (like `QUOTE` or `TRANSFER`) or a reference to a KYC process on the profile that isn&apos;t related to a specific product (like `REFRESH_CYCLE` or `REPAPERING`).Following types are available when creating a KYC Review using this endpoint:- `QUOTE`- `PROACTIVE_SEND_MONEY`- `CARD`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum KycReviewsPostRequestBody_type
    {
        [EnumMember(Value = "QUOTE")]
        #pragma warning disable CS1591
        QUOTE,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROACTIVE_SEND_MONEY")]
        #pragma warning disable CS1591
        PROACTIVE_SEND_MONEY,
        #pragma warning restore CS1591
        [EnumMember(Value = "CARD")]
        #pragma warning disable CS1591
        CARD,
        #pragma warning restore CS1591
    }
}
