// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.Cases.Item.Messages
{
    /// <summary>
    /// Builds and executes requests for operations under \cases\{caseId}\messages
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MessagesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Cases.Item.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cases/{caseId}/messages", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Cases.Item.Messages.MessagesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MessagesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cases/{caseId}/messages", rawUrl)
        {
        }
        /// <summary>
        /// Submits a new message to an existing support case. The message type determinesthe expected structure of the submission data.See the [Case submission type](/guides/product/partner/submission-types.md) guide for details on each submission type along with an example..
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionResponse"/></returns>
        /// <param name="body">Request body for submitting a message to a case.The structure of `submissionData` depends on the `type` field.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Error400BadRequest">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Error401Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Error403Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Error404NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Error422UnprocessableEntity">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.Value429ResponseContent">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionResponse?> PostAsync(global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionResponse> PostAsync(global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Wise.OpenApiClient.Models.Error400BadRequest.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Wise.OpenApiClient.Models.Error401Unauthorized.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Wise.OpenApiClient.Models.Error403Forbidden.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Wise.OpenApiClient.Models.Error404NotFound.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Wise.OpenApiClient.Models.Error422UnprocessableEntity.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Wise.OpenApiClient.Models.Value429ResponseContent.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionResponse>(requestInfo, global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Submits a new message to an existing support case. The message type determinesthe expected structure of the submission data.See the [Case submission type](/guides/product/partner/submission-types.md) guide for details on each submission type along with an example..
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Request body for submitting a message to a case.The structure of `submissionData` depends on the `type` field.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.Models.MessageSubmissionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Cases.Item.Messages.MessagesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.Cases.Item.Messages.MessagesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.Cases.Item.Messages.MessagesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
