// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V1.Accounts;
using Soenneker.Wise.OpenApiClient.V1.AddressRequirements;
using Soenneker.Wise.OpenApiClient.V1.Addresses;
using Soenneker.Wise.OpenApiClient.V1.Application;
using Soenneker.Wise.OpenApiClient.V1.Auth;
using Soenneker.Wise.OpenApiClient.V1.Cases;
using Soenneker.Wise.OpenApiClient.V1.Currencies;
using Soenneker.Wise.OpenApiClient.V1.DeliveryEstimates;
using Soenneker.Wise.OpenApiClient.V1.Facetec;
using Soenneker.Wise.OpenApiClient.V1.Me;
using Soenneker.Wise.OpenApiClient.V1.OneTimeToken;
using Soenneker.Wise.OpenApiClient.V1.Profiles;
using Soenneker.Wise.OpenApiClient.V1.Quotes;
using Soenneker.Wise.OpenApiClient.V1.Rates;
using Soenneker.Wise.OpenApiClient.V1.Settlements;
using Soenneker.Wise.OpenApiClient.V1.Simulation;
using Soenneker.Wise.OpenApiClient.V1.TransferRequirements;
using Soenneker.Wise.OpenApiClient.V1.Transfers;
using Soenneker.Wise.OpenApiClient.V1.User;
using Soenneker.Wise.OpenApiClient.V1.Users;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addresses property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Addresses.AddressesRequestBuilder Addresses
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Addresses.AddressesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The addressRequirements property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.AddressRequirements.AddressRequirementsRequestBuilder AddressRequirements
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.AddressRequirements.AddressRequirementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The application property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Application.ApplicationRequestBuilder Application
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Application.ApplicationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The auth property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Auth.AuthRequestBuilder Auth
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The cases property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Cases.CasesRequestBuilder Cases
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Cases.CasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The currencies property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Currencies.CurrenciesRequestBuilder Currencies
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Currencies.CurrenciesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deliveryEstimates property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.DeliveryEstimates.DeliveryEstimatesRequestBuilder DeliveryEstimates
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.DeliveryEstimates.DeliveryEstimatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The facetec property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Facetec.FacetecRequestBuilder Facetec
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Facetec.FacetecRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The me property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Me.MeRequestBuilder Me
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Me.MeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oneTimeToken property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.OneTimeToken.OneTimeTokenRequestBuilder OneTimeToken
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.OneTimeToken.OneTimeTokenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profiles property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesRequestBuilder Profiles
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The quotes property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Quotes.QuotesRequestBuilder Quotes
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Quotes.QuotesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The rates property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Rates.RatesRequestBuilder Rates
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Rates.RatesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settlements property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsRequestBuilder Settlements
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The simulation property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Simulation.SimulationRequestBuilder Simulation
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Simulation.SimulationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transferRequirements property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.TransferRequirements.TransferRequirementsRequestBuilder TransferRequirements
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.TransferRequirements.TransferRequirementsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transfers property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Transfers.TransfersRequestBuilder Transfers
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Transfers.TransfersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
