// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Status of the Activity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ActivityStatus
    {
        [EnumMember(Value = "REQUIRES_ATTENTION")]
        #pragma warning disable CS1591
        REQUIRES_ATTENTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_PROGRESS")]
        #pragma warning disable CS1591
        IN_PROGRESS,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPCOMING")]
        #pragma warning disable CS1591
        UPCOMING,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        COMPLETED,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        CANCELLED,
        #pragma warning restore CS1591
    }
}
