// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Occupation type - always `FREE_FORM`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddressRequest_details_occupations_format
    {
        [EnumMember(Value = "FREE_FORM")]
        #pragma warning disable CS1591
        FREE_FORM,
        #pragma warning restore CS1591
    }
}
