// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Account holder type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BalanceStatementGet200_accountHolder_type
    {
        [EnumMember(Value = "PERSONAL")]
        #pragma warning disable CS1591
        PERSONAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUSINESS")]
        #pragma warning disable CS1591
        BUSINESS,
        #pragma warning restore CS1591
    }
}
