// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BalanceMovement201ResponseStepsItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The balancesAfter property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemBalancesAfterItem>? BalancesAfter { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemBalancesAfterItem> BalancesAfter { get; set; }
#endif
        /// <summary>When the step was created.</summary>
        public DateTimeOffset? CreationTime { get; set; }
        /// <summary>The fee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemFee? Fee { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemFee Fee { get; set; }
#endif
        /// <summary>Step ID.</summary>
        public long? Id { get; set; }
        /// <summary>Exchange rate applied.</summary>
        public double? Rate { get; set; }
        /// <summary>The sourceAmount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemSourceAmount? SourceAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemSourceAmount SourceAmount { get; set; }
#endif
        /// <summary>The targetAmount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemTargetAmount? TargetAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemTargetAmount TargetAmount { get; set; }
#endif
        /// <summary>Step type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItem"/> and sets the default values.
        /// </summary>
        public BalanceMovement201ResponseStepsItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "balancesAfter", n => { BalancesAfter = n.GetCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemBalancesAfterItem>(global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemBalancesAfterItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "creationTime", n => { CreationTime = n.GetDateTimeOffsetValue(); } },
                { "fee", n => { Fee = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemFee>(global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemFee.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "rate", n => { Rate = n.GetDoubleValue(); } },
                { "sourceAmount", n => { SourceAmount = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemSourceAmount>(global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemSourceAmount.CreateFromDiscriminatorValue); } },
                { "targetAmount", n => { TargetAmount = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemTargetAmount>(global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemTargetAmount.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemBalancesAfterItem>("balancesAfter", BalancesAfter);
            writer.WriteDateTimeOffsetValue("creationTime", CreationTime);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemFee>("fee", Fee);
            writer.WriteLongValue("id", Id);
            writer.WriteDoubleValue("rate", Rate);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemSourceAmount>("sourceAmount", SourceAmount);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BalanceMovement201ResponseStepsItemTargetAmount>("targetAmount", TargetAmount);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
