// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Current batch group status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchGroupFund200ResponseStatus
    {
        [EnumMember(Value = "NEW")]
        #pragma warning disable CS1591
        NewValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
        [EnumMember(Value = "MARKED_FOR_CANCELLATION")]
        #pragma warning disable CS1591
        MarkedForCancellation,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROCESSING_CANCEL")]
        #pragma warning disable CS1591
        ProcessingCancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCELLED")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
