// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Whether this batch was submitted over the API or as a file.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BatchGroupFund200ResponseGroupType
    {
        [EnumMember(Value = "API")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "FILE")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
    }
}
