// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BeAccountIdentification : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>SWIFT BIC (Business Identifier Code) of the financial institution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bic { get; set; }
#nullable restore
#else
        public string Bic { get; set; }
#endif
        /// <summary>International Bank Account Number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Iban { get; set; }
#nullable restore
#else
        public string Iban { get; set; }
#endif
        /// <summary>Postal address of the financial institution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Iso20022Address? InstitutionAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Iso20022Address InstitutionAddress { get; set; }
#endif
        /// <summary>Name of the financial institution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstitutionName { get; set; }
#nullable restore
#else
        public string InstitutionName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.BeAccountIdentification"/> and sets the default values.
        /// </summary>
        public BeAccountIdentification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.BeAccountIdentification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.BeAccountIdentification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.BeAccountIdentification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bic", n => { Bic = n.GetStringValue(); } },
                { "iban", n => { Iban = n.GetStringValue(); } },
                { "institutionAddress", n => { InstitutionAddress = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Iso20022Address>(global::Soenneker.Wise.OpenApiClient.Models.Iso20022Address.CreateFromDiscriminatorValue); } },
                { "institutionName", n => { InstitutionName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bic", Bic);
            writer.WriteStringValue("iban", Iban);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Iso20022Address>("institutionAddress", InstitutionAddress);
            writer.WriteStringValue("institutionName", InstitutionName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
