// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BusinessProfileIndustryCategories : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Address associated with a profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Address2? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Address2 Address { get; set; }
#endif
        /// <summary>Free-form description of the business activities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessFreeFormDescription { get; set; }
#nullable restore
#else
        public string BusinessFreeFormDescription { get; set; }
#endif
        /// <summary>Registered business name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessName { get; set; }
#nullable restore
#else
        public string BusinessName { get; set; }
#endif
        /// <summary>Role of the person managing the business profile.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCompanyRole? CompanyRole { get; set; }
        /// <summary>Type of company.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyType { get; set; }
#nullable restore
#else
        public string CompanyType { get; set; }
#endif
        /// <summary>Contact information for the business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesContactDetails? ContactDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesContactDetails ContactDetails { get; set; }
#endif
        /// <summary>Timestamp when the profile was created (ISO 8601 format).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Current status of this profile.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCurrentState? CurrentState { get; set; }
        /// <summary>Primary email address for the business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Full legal name of the business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FullName { get; set; }
#nullable restore
#else
        public string FullName { get; set; }
#endif
        /// <summary>Unique identifier for the profile.</summary>
        public long? Id { get; set; }
        /// <summary>One or more industry categories classifying the business. See [Business Categories](/guides/developer/api-guides/business-categories) for the full list of valid values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? IndustryCategories { get; set; }
#nullable restore
#else
        public List<string> IndustryCategories { get; set; }
#endif
        /// <summary>An array of operational addresses for the business.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wise.OpenApiClient.Models.Address2>? OperationalAddresses { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wise.OpenApiClient.Models.Address2> OperationalAddresses { get; set; }
#endif
        /// <summary>Publicly accessible identifier for the profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicId { get; set; }
#nullable restore
#else
        public string PublicId { get; set; }
#endif
        /// <summary>Business registration number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegistrationNumber { get; set; }
#nullable restore
#else
        public string RegistrationNumber { get; set; }
#endif
        /// <summary>Type of profile.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.BusinessType? Type { get; set; }
        /// <summary>Timestamp when the profile was last updated (ISO 8601 format).</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The ID of the user associated with this profile.</summary>
        public long? UserId { get; set; }
        /// <summary>Business website URL.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Webpage { get; set; }
#nullable restore
#else
        public string Webpage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategories"/> and sets the default values.
        /// </summary>
        public BusinessProfileIndustryCategories()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategories"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategories CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategories();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Address2>(global::Soenneker.Wise.OpenApiClient.Models.Address2.CreateFromDiscriminatorValue); } },
                { "businessFreeFormDescription", n => { BusinessFreeFormDescription = n.GetStringValue(); } },
                { "businessName", n => { BusinessName = n.GetStringValue(); } },
                { "companyRole", n => { CompanyRole = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCompanyRole>(); } },
                { "companyType", n => { CompanyType = n.GetStringValue(); } },
                { "contactDetails", n => { ContactDetails = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesContactDetails>(global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesContactDetails.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currentState", n => { CurrentState = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCurrentState>(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "fullName", n => { FullName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "industryCategories", n => { IndustryCategories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "operationalAddresses", n => { OperationalAddresses = n.GetCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.Address2>(global::Soenneker.Wise.OpenApiClient.Models.Address2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "publicId", n => { PublicId = n.GetStringValue(); } },
                { "registrationNumber", n => { RegistrationNumber = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetLongValue(); } },
                { "webpage", n => { Webpage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Address2>("address", Address);
            writer.WriteStringValue("businessFreeFormDescription", BusinessFreeFormDescription);
            writer.WriteStringValue("businessName", BusinessName);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCompanyRole>("companyRole", CompanyRole);
            writer.WriteStringValue("companyType", CompanyType);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesContactDetails>("contactDetails", ContactDetails);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessProfileIndustryCategoriesCurrentState>("currentState", CurrentState);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("fullName", FullName);
            writer.WriteLongValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<string>("industryCategories", IndustryCategories);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.Address2>("operationalAddresses", OperationalAddresses);
            writer.WriteStringValue("publicId", PublicId);
            writer.WriteStringValue("registrationNumber", RegistrationNumber);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.BusinessType>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteLongValue("userId", UserId);
            writer.WriteStringValue("webpage", Webpage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
