// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Type of profile.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BusinessProfile_type
    {
        [EnumMember(Value = "BUSINESS")]
        #pragma warning disable CS1591
        BUSINESS,
        #pragma warning restore CS1591
    }
}
