// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>The network of the card program:- `MASTERCARD`- `VISA`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardOrderProgramsGet200ResponseCardProgramsItemScheme
    {
        [EnumMember(Value = "MASTERCARD")]
        #pragma warning disable CS1591
        Mastercard,
        #pragma warning restore CS1591
        [EnumMember(Value = "VISA")]
        #pragma warning disable CS1591
        Visa,
        #pragma warning restore CS1591
    }
}
