// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// The Card resource represents a Wise card linked to a profile.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Card : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Bank identification number (BIN) of the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankIdentificationNumber { get; set; }
#nullable restore
#else
        public string BankIdentificationNumber { get; set; }
#endif
        /// <summary>Name of the card holder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardHolderName { get; set; }
#nullable restore
#else
        public string CardHolderName { get; set; }
#endif
        /// <summary>Card program details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Card_cardProgram? CardProgram { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Card_cardProgram CardProgram { get; set; }
#endif
        /// <summary>Client ID of the partner that issued the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>Time when the card was created.</summary>
        public DateTimeOffset? CreationTime { get; set; }
        /// <summary>Date when the card will expire.</summary>
        public DateTimeOffset? ExpiryDate { get; set; }
        /// <summary>Last 4 digits of the card number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastFourDigits { get; set; }
#nullable restore
#else
        public string LastFourDigits { get; set; }
#endif
        /// <summary>Time when the card was last modified.</summary>
        public DateTimeOffset? ModificationTime { get; set; }
        /// <summary>Phone number associated with the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PhoneNumber { get; set; }
#nullable restore
#else
        public string PhoneNumber { get; set; }
#endif
        /// <summary>Profile ID that owns this card.</summary>
        public long? ProfileId { get; set; }
        /// <summary>Current status of the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Card_status? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Card_status Status { get; set; }
#endif
        /// <summary>Unique identifier for the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Token { get; set; }
#nullable restore
#else
        public string Token { get; set; }
#endif
        /// <summary>Method with which physical card spending permissions can be unlocked. One of:- `WITH_PARTNER_API` - Unlock via Partner API- `WITH_FIRST_CHIP_AND_PIN_TRANSACTION` - Unlock with first chip and PIN transaction- `NONE` - Not applicable (for virtual cards)</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Card_unlockSpendingPermissions? UnlockSpendingPermissions { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.Card"/> and sets the default values.
        /// </summary>
        public Card()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.Card"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.Card CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.Card();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankIdentificationNumber", n => { BankIdentificationNumber = n.GetStringValue(); } },
                { "cardHolderName", n => { CardHolderName = n.GetStringValue(); } },
                { "cardProgram", n => { CardProgram = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Card_cardProgram>(global::Soenneker.Wise.OpenApiClient.Models.Card_cardProgram.CreateFromDiscriminatorValue); } },
                { "clientId", n => { ClientId = n.GetStringValue(); } },
                { "creationTime", n => { CreationTime = n.GetDateTimeOffsetValue(); } },
                { "expiryDate", n => { ExpiryDate = n.GetDateTimeOffsetValue(); } },
                { "lastFourDigits", n => { LastFourDigits = n.GetStringValue(); } },
                { "modificationTime", n => { ModificationTime = n.GetDateTimeOffsetValue(); } },
                { "phoneNumber", n => { PhoneNumber = n.GetStringValue(); } },
                { "profileId", n => { ProfileId = n.GetLongValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Card_status>(global::Soenneker.Wise.OpenApiClient.Models.Card_status.CreateFromDiscriminatorValue); } },
                { "token", n => { Token = n.GetStringValue(); } },
                { "unlockSpendingPermissions", n => { UnlockSpendingPermissions = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Card_unlockSpendingPermissions>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bankIdentificationNumber", BankIdentificationNumber);
            writer.WriteStringValue("cardHolderName", CardHolderName);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Card_cardProgram>("cardProgram", CardProgram);
            writer.WriteStringValue("clientId", ClientId);
            writer.WriteDateTimeOffsetValue("creationTime", CreationTime);
            writer.WriteDateTimeOffsetValue("expiryDate", ExpiryDate);
            writer.WriteStringValue("lastFourDigits", LastFourDigits);
            writer.WriteDateTimeOffsetValue("modificationTime", ModificationTime);
            writer.WriteStringValue("phoneNumber", PhoneNumber);
            writer.WriteLongValue("profileId", ProfileId);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Card_status>("status", Status);
            writer.WriteStringValue("token", Token);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Card_unlockSpendingPermissions>("unlockSpendingPermissions", UnlockSpendingPermissions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
