// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CardStatusValue
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACTIVE")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "INACTIVE")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "BLOCKED")]
        #pragma warning disable CS1591
        Blocked,
        #pragma warning restore CS1591
        [EnumMember(Value = "FROZEN")]
        #pragma warning disable CS1591
        Frozen,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTNER_SUSPENDED")]
        #pragma warning disable CS1591
        PartnerSuspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "PURGED")]
        #pragma warning disable CS1591
        Purged,
        #pragma warning restore CS1591
    }
}
