// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Card network scheme.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Card_cardProgram_scheme
    {
        [EnumMember(Value = "VISA")]
        #pragma warning disable CS1591
        VISA,
        #pragma warning restore CS1591
        [EnumMember(Value = "MASTERCARD")]
        #pragma warning disable CS1591
        MASTERCARD,
        #pragma warning restore CS1591
    }
}
