// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>[Type](/api-reference/card-transaction#card-transaction-type) of the transaction. One of:- `ACCOUNT_CREDIT`- `ACCOUNT_FUNDING`- `CASH_ADVANCE`- `CASH_WITHDRAWAL`- `CHARGEBACK`- `CREDIT_TRANSACTION`- `ECOM_PURCHASE`- `POS_PURCHASE`- `REFUND`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardTransaction_type
    {
        [EnumMember(Value = "ACCOUNT_CREDIT")]
        #pragma warning disable CS1591
        ACCOUNT_CREDIT,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_FUNDING")]
        #pragma warning disable CS1591
        ACCOUNT_FUNDING,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH_ADVANCE")]
        #pragma warning disable CS1591
        CASH_ADVANCE,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH_WITHDRAWAL")]
        #pragma warning disable CS1591
        CASH_WITHDRAWAL,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHARGEBACK")]
        #pragma warning disable CS1591
        CHARGEBACK,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_TRANSACTION")]
        #pragma warning disable CS1591
        CREDIT_TRANSACTION,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECOM_PURCHASE")]
        #pragma warning disable CS1591
        ECOM_PURCHASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "POS_PURCHASE")]
        #pragma warning disable CS1591
        POS_PURCHASE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUND")]
        #pragma warning disable CS1591
        REFUND,
        #pragma warning restore CS1591
    }
}
