// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>[Type](/api-reference/card-transaction#card-transaction-type) of the transaction. One of:- `ACCOUNT_CREDIT`- `ACCOUNT_FUNDING`- `CASH_ADVANCE`- `CASH_WITHDRAWAL`- `CHARGEBACK`- `CREDIT_TRANSACTION`- `ECOM_PURCHASE`- `POS_PURCHASE`- `REFUND`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CardTransactionType
    {
        [EnumMember(Value = "ACCOUNT_CREDIT")]
        #pragma warning disable CS1591
        AccountCredit,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_FUNDING")]
        #pragma warning disable CS1591
        AccountFunding,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH_ADVANCE")]
        #pragma warning disable CS1591
        CashAdvance,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH_WITHDRAWAL")]
        #pragma warning disable CS1591
        CashWithdrawal,
        #pragma warning restore CS1591
        [EnumMember(Value = "CHARGEBACK")]
        #pragma warning disable CS1591
        Chargeback,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREDIT_TRANSACTION")]
        #pragma warning disable CS1591
        CreditTransaction,
        #pragma warning restore CS1591
        [EnumMember(Value = "ECOM_PURCHASE")]
        #pragma warning disable CS1591
        EcomPurchase,
        #pragma warning restore CS1591
        [EnumMember(Value = "POS_PURCHASE")]
        #pragma warning disable CS1591
        PosPurchase,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUND")]
        #pragma warning disable CS1591
        Refund,
        #pragma warning restore CS1591
    }
}
