// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// A support case with its complete details including messages and references.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Case2 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>&quot;Timestamp when the case was created.Format: ISO 8601 datetime without timezone (YYYY-MM-DDTHH:mm:ss.SSS).&quot;</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Partner-created identifier for this case, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Unique identifier of the case.</summary>
        public long? Id { get; set; }
        /// <summary>List of messages associated with this case.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wise.OpenApiClient.Models.CaseMessage>? Messages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wise.OpenApiClient.Models.CaseMessage> Messages { get; set; }
#endif
        /// <summary>The profile ID associated with this case.</summary>
        public long? ProfileId { get; set; }
        /// <summary>Reference information linking the case to a related entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Case2Reference? Reference { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Case2Reference Reference { get; set; }
#endif
        /// <summary>The current status of the support case.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Case2Status? Status { get; set; }
        /// <summary>The sub-type of the support case.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Case2SubType? SubType { get; set; }
        /// <summary>The type of the support case.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Case2Type? Type { get; set; }
        /// <summary>&quot;Timestamp when the case was last updated.Format: ISO 8601 datetime without timezone (YYYY-MM-DDTHH:mm:ss.SSS).&quot;</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.Case2"/> and sets the default values.
        /// </summary>
        public Case2()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.Case2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.Case2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.Case2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "messages", n => { Messages = n.GetCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.CaseMessage>(global::Soenneker.Wise.OpenApiClient.Models.CaseMessage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profileId", n => { ProfileId = n.GetLongValue(); } },
                { "reference", n => { Reference = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Reference>(global::Soenneker.Wise.OpenApiClient.Models.Case2Reference.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Status>(); } },
                { "subType", n => { SubType = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2SubType>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Type>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteLongValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.CaseMessage>("messages", Messages);
            writer.WriteLongValue("profileId", ProfileId);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Reference>("reference", Reference);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Status>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2SubType>("subType", SubType);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Case2Type>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
