// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>OAuth 2.0 grant type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClientCredentialsGrantGrantType
    {
        [EnumMember(Value = "client_credentials")]
        #pragma warning disable CS1591
        ClientCredentials,
        #pragma warning restore CS1591
    }
}
