// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// Delivery estimation details - i.e. a speed estimate
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComparisonV3_providers_quotes_deliveryEstimation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Estimated transaction delivery date range</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_deliveryDate? DeliveryDate { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_deliveryDate DeliveryDate { get; set; }
#endif
        /// <summary>Duration range</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_duration? Duration { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_duration Duration { get; set; }
#endif
        /// <summary>Whether the duration is in calendar days, business days, or same day</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_durationType? DurationType { get; set; }
        /// <summary>Whether a provider publicly surfaces a speed estimate or not</summary>
        public bool? ProviderGivesEstimate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation"/> and sets the default values.
        /// </summary>
        public ComparisonV3_providers_quotes_deliveryEstimation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deliveryDate", n => { DeliveryDate = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_deliveryDate>(global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_deliveryDate.CreateFromDiscriminatorValue); } },
                { "duration", n => { Duration = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_duration>(global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_duration.CreateFromDiscriminatorValue); } },
                { "durationType", n => { DurationType = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_durationType>(); } },
                { "providerGivesEstimate", n => { ProviderGivesEstimate = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_deliveryDate>("deliveryDate", DeliveryDate);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_duration>("duration", Duration);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.ComparisonV3_providers_quotes_deliveryEstimation_durationType>("durationType", DurationType);
            writer.WriteBoolValue("providerGivesEstimate", ProviderGivesEstimate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
