// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DeliveryUpdateRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The delivery signal to simulate. Must be a member of `delivery_update_path`, but need not be its last item.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestDeliveryUpdate? DeliveryUpdate { get; set; }
        /// <summary>Delivery signals supported by the simulated route, not a history of events.Select one or more distinct values in this progression order:`partner_accepted`, `recipient_provider_accepted`, `scheme_settled`,`account_credited`, `funds_available`. Values may be skipped.The service validates the order and requires this array to contain `delivery_update`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdate?>? DeliveryUpdatePath { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdate?> DeliveryUpdatePath { get; set; }
#endif
        /// <summary>Optional estimated delivery time. May be omitted or null. Published timestamps are truncated to milliseconds.</summary>
        public DateTimeOffset? EstimatedDeliveryAt { get; set; }
        /// <summary>Payment scheme to include in the observation. May be omitted or null.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestScheme? Scheme { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequest"/> and sets the default values.
        /// </summary>
        public DeliveryUpdateRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "delivery_update", n => { DeliveryUpdate = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestDeliveryUpdate>(); } },
                { "delivery_update_path", n => { DeliveryUpdatePath = n.GetCollectionOfEnumValues<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdate>()?.AsList(); } },
                { "estimated_delivery_at", n => { EstimatedDeliveryAt = n.GetDateTimeOffsetValue(); } },
                { "scheme", n => { Scheme = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestScheme>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestDeliveryUpdate>("delivery_update", DeliveryUpdate);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdate>("delivery_update_path", DeliveryUpdatePath);
            writer.WriteDateTimeOffsetValue("estimated_delivery_at", EstimatedDeliveryAt);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.DeliveryUpdateRequestScheme>("scheme", Scheme);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
