// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DirectDebitAccountGetTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ACH")]
        #pragma warning disable CS1591
        Ach,
        #pragma warning restore CS1591
        [EnumMember(Value = "EFT")]
        #pragma warning disable CS1591
        Eft,
        #pragma warning restore CS1591
    }
}
