// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Dispute detailed status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DisputeSubStatus
    {
        [EnumMember(Value = "SUBMITTED")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "IN_REVIEW")]
        #pragma warning disable CS1591
        InReview,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUNDED")]
        #pragma warning disable CS1591
        Refunded,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECTED")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITHDRAWN")]
        #pragma warning disable CS1591
        Withdrawn,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONFIRMED")]
        #pragma warning disable CS1591
        Confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFUND_IN_PROGRESS")]
        #pragma warning disable CS1591
        RefundInProgress,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTEMPTING_RECOVERY")]
        #pragma warning disable CS1591
        AttemptingRecovery,
        #pragma warning restore CS1591
        [EnumMember(Value = "RECOVERY_UNSUCCESSFUL")]
        #pragma warning disable CS1591
        RecoveryUnsuccessful,
        #pragma warning restore CS1591
    }
}
