// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Dispute : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the dispute can be withdrawn.</summary>
        public bool? CanWithdraw { get; set; }
        /// <summary>Time when the dispute was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Creator of the dispute. Currently set to the user ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Unique identifier of the dispute.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Time when the dispute was last updated.</summary>
        public DateTimeOffset? LastUpdatedAt { get; set; }
        /// <summary>Profile ID.</summary>
        public long? ProfileId { get; set; }
        /// <summary>Dispute reason code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>Dispute overall status.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Dispute_status? Status { get; set; }
        /// <summary>Explanation for `subStatus`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusMessage { get; set; }
#nullable restore
#else
        public string StatusMessage { get; set; }
#endif
        /// <summary>Dispute detailed status.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.Dispute_subStatus? SubStatus { get; set; }
        /// <summary>Card transaction ID.</summary>
        public long? TransactionId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.Dispute"/> and sets the default values.
        /// </summary>
        public Dispute()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.Dispute"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.Dispute CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.Dispute();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canWithdraw", n => { CanWithdraw = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "lastUpdatedAt", n => { LastUpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "profileId", n => { ProfileId = n.GetLongValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Dispute_status>(); } },
                { "statusMessage", n => { StatusMessage = n.GetStringValue(); } },
                { "subStatus", n => { SubStatus = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Dispute_subStatus>(); } },
                { "transactionId", n => { TransactionId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("canWithdraw", CanWithdraw);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("id", Id);
            writer.WriteDateTimeOffsetValue("lastUpdatedAt", LastUpdatedAt);
            writer.WriteLongValue("profileId", ProfileId);
            writer.WriteStringValue("reason", Reason);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Dispute_status>("status", Status);
            writer.WriteStringValue("statusMessage", StatusMessage);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.Dispute_subStatus>("subStatus", SubStatus);
            writer.WriteLongValue("transactionId", TransactionId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
