// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance"/>, <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund"/>, <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FundingRequest : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance? FundingRequestBalance { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance FundingRequestBalance { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund? FundingRequestTrustedPreFund { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund FundingRequestTrustedPreFund { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk? FundingRequestTrustedPreFundBulk { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk FundingRequestTrustedPreFundBulk { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.FundingRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.FundingRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Wise.OpenApiClient.Models.FundingRequest();
            if("BALANCE".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FundingRequestBalance = new global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance();
            }
            else if("FundingRequestTrustedPreFund".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FundingRequestTrustedPreFund = new global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund();
            }
            else if("FundingRequestTrustedPreFundBulk".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.FundingRequestTrustedPreFundBulk = new global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(FundingRequestBalance != null)
            {
                return FundingRequestBalance.GetFieldDeserializers();
            }
            else if(FundingRequestTrustedPreFund != null)
            {
                return FundingRequestTrustedPreFund.GetFieldDeserializers();
            }
            else if(FundingRequestTrustedPreFundBulk != null)
            {
                return FundingRequestTrustedPreFundBulk.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(FundingRequestBalance != null)
            {
                writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.FundingRequestBalance>(null, FundingRequestBalance);
            }
            else if(FundingRequestTrustedPreFund != null)
            {
                writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFund>(null, FundingRequestTrustedPreFund);
            }
            else if(FundingRequestTrustedPreFundBulk != null)
            {
                writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.FundingRequestTrustedPreFundBulk>(null, FundingRequestTrustedPreFundBulk);
            }
        }
    }
}
#pragma warning restore CS0618
