// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>The type of identifier used to look up the transfer.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GpiTrackingIdentifierType
    {
        [EnumMember(Value = "UETR")]
        #pragma warning disable CS1591
        Uetr,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSFER_ID")]
        #pragma warning disable CS1591
        TransferId,
        #pragma warning restore CS1591
    }
}
