// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Method of payment.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PayInDetailsType
    {
        [EnumMember(Value = "bank_transfer")]
        #pragma warning disable CS1591
        BankTransfer,
        #pragma warning restore CS1591
    }
}
