// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Context of the update.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProfileBusinessRepresentativeUpdateRequestUpdateContext
    {
        [EnumMember(Value = "UPDATE_DETAILS")]
        #pragma warning disable CS1591
        UpdateDetails,
        #pragma warning restore CS1591
        [EnumMember(Value = "TRANSFER_OF_AUTHORISATION")]
        #pragma warning disable CS1591
        TransferOfAuthorisation,
        #pragma warning restore CS1591
    }
}
