// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Token service provider.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PushProvisioningGooglePayGet200ResponseTokenServiceProvider
    {
        [EnumMember(Value = "TOKEN_PROVIDER_VISA")]
        #pragma warning disable CS1591
        TokenProviderVisa,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOKEN_PROVIDER_MASTERCARD")]
        #pragma warning disable CS1591
        TokenProviderMastercard,
        #pragma warning restore CS1591
    }
}
