// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// The `accountSummary` and `longAccountSummary` fields can be used to represent the recipient&apos;s details in your UI. The `displayFields` array allows you to build a UI containing all the dynamic fields of a recipient individually. In order to use these fields, you would need to POST using the v1 endpoint to create the recipient account, and then GET using the v2 endpoint to retrieve these fields.The v2 resource also includes the `hash` field that can be used to track recipient details changes. This is useful for re-running any validation checks your system performs on the recipient, for example against fraud engines. The hash will remain constant unless the recipient&apos;s name or information in the `details` object changes.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Recipient : IAdditionalDataHolder, IParsable
    {
        /// <summary>Summary of account details for ease of lookup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountSummary { get; set; }
#nullable restore
#else
        public string AccountSummary { get; set; }
#endif
        /// <summary>Status of the recipient.</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Map of key lookup fields on the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_commonFieldMap? CommonFieldMap { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_commonFieldMap CommonFieldMap { get; set; }
#endif
        /// <summary>Verification results for the recipient&apos;s details. Only populated for currencies with recipient verification enabled (KRW, INR, IDR, EUR). See the [Verifying Recipient Details](/guides/developer/api-guides/recipient-verification) guide for how to handle these.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_confirmations? Confirmations { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_confirmations Confirmations { get; set; }
#endif
        /// <summary>2 character country code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>Account entity that owns the recipient account.</summary>
        public long? CreatorId { get; set; }
        /// <summary>3 character currency code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Account details (currency/type-specific). The keys present vary by currency route and recipient type (e.g., sort code, IBAN, SWIFT, email).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_details? Details { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_details Details { get; set; }
#endif
        /// <summary>Lookup fields (key/label/value) for rendering a UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Wise.OpenApiClient.Models.Recipient_displayFields>? DisplayFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Wise.OpenApiClient.Models.Recipient_displayFields> DisplayFields { get; set; }
#endif
        /// <summary>Account hash for change tracking.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Hash { get; set; }
#nullable restore
#else
        public string Hash { get; set; }
#endif
        /// <summary>ID of the recipient. Use the returned id as `sourceAccount` to specify the refund recipient when creating transfers.</summary>
        public long? Id { get; set; }
        /// <summary>Indicates whether recipient is internal.</summary>
        public bool? IsInternal { get; set; }
        /// <summary>Entity type of recipient.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalEntityType { get; set; }
#nullable restore
#else
        public string LegalEntityType { get; set; }
#endif
        /// <summary>Account details summary.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LongAccountSummary { get; set; }
#nullable restore
#else
        public string LongAccountSummary { get; set; }
#endif
        /// <summary>Recipient name details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_name? Name { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Recipient_name Name { get; set; }
#endif
        /// <summary>If recipient account belongs to profile owner.</summary>
        public bool? OwnedByCustomer { get; set; }
        /// <summary>Specific profile that owns the recipient account.</summary>
        public long? ProfileId { get; set; }
        /// <summary>Recipient type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.Recipient"/> and sets the default values.
        /// </summary>
        public Recipient()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.Recipient"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.Recipient CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.Recipient();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountSummary", n => { AccountSummary = n.GetStringValue(); } },
                { "active", n => { Active = n.GetBoolValue(); } },
                { "commonFieldMap", n => { CommonFieldMap = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_commonFieldMap>(global::Soenneker.Wise.OpenApiClient.Models.Recipient_commonFieldMap.CreateFromDiscriminatorValue); } },
                { "confirmations", n => { Confirmations = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_confirmations>(global::Soenneker.Wise.OpenApiClient.Models.Recipient_confirmations.CreateFromDiscriminatorValue); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "creatorId", n => { CreatorId = n.GetLongValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "details", n => { Details = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_details>(global::Soenneker.Wise.OpenApiClient.Models.Recipient_details.CreateFromDiscriminatorValue); } },
                { "displayFields", n => { DisplayFields = n.GetCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.Recipient_displayFields>(global::Soenneker.Wise.OpenApiClient.Models.Recipient_displayFields.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hash", n => { Hash = n.GetStringValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "isInternal", n => { IsInternal = n.GetBoolValue(); } },
                { "legalEntityType", n => { LegalEntityType = n.GetStringValue(); } },
                { "longAccountSummary", n => { LongAccountSummary = n.GetStringValue(); } },
                { "name", n => { Name = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_name>(global::Soenneker.Wise.OpenApiClient.Models.Recipient_name.CreateFromDiscriminatorValue); } },
                { "ownedByCustomer", n => { OwnedByCustomer = n.GetBoolValue(); } },
                { "profileId", n => { ProfileId = n.GetLongValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountSummary", AccountSummary);
            writer.WriteBoolValue("active", Active);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_commonFieldMap>("commonFieldMap", CommonFieldMap);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_confirmations>("confirmations", Confirmations);
            writer.WriteStringValue("country", Country);
            writer.WriteLongValue("creatorId", CreatorId);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_details>("details", Details);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Wise.OpenApiClient.Models.Recipient_displayFields>("displayFields", DisplayFields);
            writer.WriteStringValue("hash", Hash);
            writer.WriteLongValue("id", Id);
            writer.WriteBoolValue("isInternal", IsInternal);
            writer.WriteStringValue("legalEntityType", LegalEntityType);
            writer.WriteStringValue("longAccountSummary", LongAccountSummary);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Recipient_name>("name", Name);
            writer.WriteBoolValue("ownedByCustomer", OwnedByCustomer);
            writer.WriteLongValue("profileId", ProfileId);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
