// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>The reason for closing the case. Required when `status` is `CLOSE`.- `EXPIRED`: The case expired without resolution- `INVALIDATED`: The case was determined to be invalid- `ABORTED`: The case was aborted/cancelled- `COMPLETED`: The case was successfully resolved</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SimulateSanctionCaseRequestClosingReason
    {
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVALIDATED")]
        #pragma warning disable CS1591
        Invalidated,
        #pragma warning restore CS1591
        [EnumMember(Value = "ABORTED")]
        #pragma warning disable CS1591
        Aborted,
        #pragma warning restore CS1591
        [EnumMember(Value = "COMPLETED")]
        #pragma warning disable CS1591
        Completed,
        #pragma warning restore CS1591
    }
}
