// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Submission data for sanction hit cases. Used for:- DEPOSIT_SANCTION_HIT_SUBMISSION- REFERENCE_SANCTION_HIT_SUBMISSION- RECIPIENT_SANCTION_HIT_SUBMISSION**Important**: Only ONE of the entity types should be provided per submission.### Validation Rules by Submission Type:**DEPOSIT_SANCTION_HIT_SUBMISSION**:- Must contain either `individual` OR `organisation` (exactly one)**RECIPIENT_SANCTION_HIT_SUBMISSION**:- Must contain either `individual` OR `organisation` (exactly one)- If `individual`, `countryOfResidenceIso3` is REQUIRED**REFERENCE_SANCTION_HIT_SUBMISSION**:- Must contain exactly one of: `individual`, `organisation`, `multiple`, `vessel`, or `other`- If `individual`, `countryOfResidenceIso3` is REQUIRED&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubmissionDataSanctionHit : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The individual property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionIndividualIndividual? Individual { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionIndividualIndividual Individual { get; set; }
#endif
        /// <summary>The multiple property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionMultipleMultiple? Multiple { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionMultipleMultiple Multiple { get; set; }
#endif
        /// <summary>The organisation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionOrganisationOrganisation? Organisation { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionOrganisationOrganisation Organisation { get; set; }
#endif
        /// <summary>The other property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionOtherOther? Other { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionOtherOther Other { get; set; }
#endif
        /// <summary>Union discriminator</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The vessel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionVesselVessel? Vessel { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubmissionVesselVessel Vessel { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.SubmissionDataSanctionHit"/> and sets the default values.
        /// </summary>
        public SubmissionDataSanctionHit()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.SubmissionDataSanctionHit"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.SubmissionDataSanctionHit CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.SubmissionDataSanctionHit();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "individual", n => { Individual = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionIndividualIndividual>(global::Soenneker.Wise.OpenApiClient.Models.SubmissionIndividualIndividual.CreateFromDiscriminatorValue); } },
                { "multiple", n => { Multiple = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionMultipleMultiple>(global::Soenneker.Wise.OpenApiClient.Models.SubmissionMultipleMultiple.CreateFromDiscriminatorValue); } },
                { "organisation", n => { Organisation = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionOrganisationOrganisation>(global::Soenneker.Wise.OpenApiClient.Models.SubmissionOrganisationOrganisation.CreateFromDiscriminatorValue); } },
                { "other", n => { Other = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionOtherOther>(global::Soenneker.Wise.OpenApiClient.Models.SubmissionOtherOther.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "vessel", n => { Vessel = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionVesselVessel>(global::Soenneker.Wise.OpenApiClient.Models.SubmissionVesselVessel.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionIndividualIndividual>("individual", Individual);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionMultipleMultiple>("multiple", Multiple);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionOrganisationOrganisation>("organisation", Organisation);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionOtherOther>("other", Other);
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubmissionVesselVessel>("vessel", Vessel);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
