// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubscriptionRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The delivery property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest_delivery? Delivery { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest_delivery Delivery { get; set; }
#endif
        /// <summary>A custom name for your webhook to ease with identification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>[Choose from a list of available events](/guides/developer/webhooks/event-types).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TriggerOn { get; set; }
#nullable restore
#else
        public string TriggerOn { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest"/> and sets the default values.
        /// </summary>
        public SubscriptionRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "delivery", n => { Delivery = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest_delivery>(global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest_delivery.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "trigger_on", n => { TriggerOn = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.SubscriptionRequest_delivery>("delivery", Delivery);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("trigger_on", TriggerOn);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
