// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Type of sender. Required from March 2026 for Correspondent Send integrations</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferRequirementsValidate_originatorLegalEntityType
    {
        [EnumMember(Value = "PRIVATE")]
        #pragma warning disable CS1591
        PRIVATE,
        #pragma warning restore CS1591
        [EnumMember(Value = "BUSINESS")]
        #pragma warning disable CS1591
        BUSINESS,
        #pragma warning restore CS1591
    }
}
