// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class V40021Data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Current payment initiation state.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.V40021DataCurrentStatus? CurrentStatus { get; set; }
        /// <summary>When the payment initiation state change occurred.</summary>
        public DateTimeOffset? OccurredAt { get; set; }
        /// <summary>Previous payment initiation state.</summary>
        public global::Soenneker.Wise.OpenApiClient.Models.V40021DataPreviousStatus? PreviousStatus { get; set; }
        /// <summary>The resource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.V40021DataResource? Resource { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.V40021DataResource Resource { get; set; }
#endif
        /// <summary>Return code of the underlying payment system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReturnCode { get; set; }
#nullable restore
#else
        public string ReturnCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.V40021Data"/> and sets the default values.
        /// </summary>
        public V40021Data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.V40021Data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.V40021Data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.V40021Data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "current_status", n => { CurrentStatus = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataCurrentStatus>(); } },
                { "occurred_at", n => { OccurredAt = n.GetDateTimeOffsetValue(); } },
                { "previous_status", n => { PreviousStatus = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataPreviousStatus>(); } },
                { "resource", n => { Resource = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataResource>(global::Soenneker.Wise.OpenApiClient.Models.V40021DataResource.CreateFromDiscriminatorValue); } },
                { "return_code", n => { ReturnCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataCurrentStatus>("current_status", CurrentStatus);
            writer.WriteDateTimeOffsetValue("occurred_at", OccurredAt);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataPreviousStatus>("previous_status", PreviousStatus);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.V40021DataResource>("resource", Resource);
            writer.WriteStringValue("return_code", ReturnCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
