// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>The type of the webhook being sent.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum V40022DataType
    {
        [EnumMember(Value = "STATUS_UPDATED")]
        #pragma warning disable CS1591
        StatusUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEW_COMMENT")]
        #pragma warning disable CS1591
        NewComment,
        #pragma warning restore CS1591
        [EnumMember(Value = "NEW_CASE")]
        #pragma warning disable CS1591
        NewCase,
        #pragma warning restore CS1591
    }
}
