// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>If the type is `ACCOUNT_SUSPENSION`, it is possible to appeal the deactivation by contacting Wise.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum V40018DataDeactivationType
    {
        [EnumMember(Value = "ACCOUNT_SUSPENSION")]
        #pragma warning disable CS1591
        AccountSuspension,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_CLOSURE")]
        #pragma warning disable CS1591
        AccountClosure,
        #pragma warning restore CS1591
    }
}
