// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>Reason the breach was closed. Null if state is `OPEN`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum V40012DataClosingReason
    {
        [EnumMember(Value = "AUTOMATICALLY_RESOLVED")]
        #pragma warning disable CS1591
        AutomaticallyResolved,
        #pragma warning restore CS1591
        [EnumMember(Value = "MANUALLY_RESOLVED")]
        #pragma warning disable CS1591
        ManuallyResolved,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
