// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.Models
{
    /// <summary>
    /// Ultimate recipient.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V430DataResourceRecipient : IAdditionalDataHolder, IParsable
    {
        /// <summary>An IBAN, BBAN, AccountId, or another account descriptor.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Account { get; set; }
#nullable restore
#else
        public string Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Structured address details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.Address5? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.Address5 Address { get; set; }
#endif
        /// <summary>Bank or financial institution details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Wise.OpenApiClient.Models.BankDetails2? BankDetails { get; set; }
#nullable restore
#else
        public global::Soenneker.Wise.OpenApiClient.Models.BankDetails2 BankDetails { get; set; }
#endif
        /// <summary>Party name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.Models.V430DataResourceRecipient"/> and sets the default values.
        /// </summary>
        public V430DataResourceRecipient()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.Models.V430DataResourceRecipient"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.Models.V430DataResourceRecipient CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.Models.V430DataResourceRecipient();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetStringValue(); } },
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Address5>(global::Soenneker.Wise.OpenApiClient.Models.Address5.CreateFromDiscriminatorValue); } },
                { "bank_details", n => { BankDetails = n.GetObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BankDetails2>(global::Soenneker.Wise.OpenApiClient.Models.BankDetails2.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("account", Account);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Address5>("address", Address);
            writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.BankDetails2>("bank_details", BankDetails);
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
