// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay
{
    /// <summary>
    /// Builds and executes requests for operations under \twcard-data\v1\push-provisioning\encrypted-payload\apple-pay
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApplePayRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplePayRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1/push-provisioning/encrypted-payload/apple-pay", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApplePayRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/twcard-data/v1/push-provisioning/encrypted-payload/apple-pay", rawUrl)
        {
        }
        /// <summary>
        /// Returns encrypted cardholder information and other metadata needed for Apple Pay push provisioning.{% admonition type=&quot;warning&quot; %}This API is not available for sandbox testing.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Wise.OpenApiClient.Models.ApplePay429Error">When receiving a 429 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostResponse?> PostAsync(global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostResponse> PostAsync(global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "429", global::Soenneker.Wise.OpenApiClient.Models.ApplePay429Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostResponse>(requestInfo, global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns encrypted cardholder information and other metadata needed for Apple Pay push provisioning.{% admonition type=&quot;warning&quot; %}This API is not available for sandbox testing.{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.TwcardData.V1.PushProvisioning.EncryptedPayload.ApplePay.ApplePayRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
