// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\transfers\{transferId}\cancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/transfers/{transferId}/cancel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/transfers/{transferId}/cancel", rawUrl)
        {
        }
        /// <summary>
        /// Transfers may be cancelled up until the transfer has been processed and funds converted. Cancellation is final — it cannot be undone.{% admonition type=&quot;info&quot; name=&quot;When can a transfer be cancelled?&quot; %}A transfer can only be cancelled programmatically via the API if it meets **all** of the following criteria:- The transfer is not in `funds_converted` or later state.- There are no processing problems with the transfer.If the transfer does not meet these criteria, the API will return a **409 Conflict** error with the code `transfer.cancellation.not.allowed`.For more information about transfer states, see [Tracking Transfers](/guides/product/send-money/tracking-transfers#transfer-statuses).{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse?> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse> PutAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPutRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse>(requestInfo, global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Transfers may be cancelled up until the transfer has been processed and funds converted. Cancellation is final — it cannot be undone.{% admonition type=&quot;info&quot; name=&quot;When can a transfer be cancelled?&quot; %}A transfer can only be cancelled programmatically via the API if it meets **all** of the following criteria:- The transfer is not in `funds_converted` or later state.- There are no processing problems with the transfer.If the transfer does not meet these criteria, the API will return a **409 Conflict** error with the code `transfer.cancellation.not.allowed`.For more information about transfer states, see [Tracking Transfers](/guides/product/send-money/tracking-transfers#transfer-statuses).{% /admonition %}
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer"/>, <see cref="global::Soenneker.Wise.OpenApiClient.Models.Transfer"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CancelPutResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer? OriginatorTransfer { get; set; }
#nullable restore
#else
            public global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer OriginatorTransfer { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Wise.OpenApiClient.Models.Transfer"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Wise.OpenApiClient.Models.Transfer? Transfer { get; set; }
#nullable restore
#else
            public global::Soenneker.Wise.OpenApiClient.Models.Transfer Transfer { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Wise.OpenApiClient.V1.Transfers.Item.Cancel.CancelRequestBuilder.CancelPutResponse();
                if("originator-transfer".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.OriginatorTransfer = new global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer();
                }
                else if("transfer".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Transfer = new global::Soenneker.Wise.OpenApiClient.Models.Transfer();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(OriginatorTransfer != null)
                {
                    return OriginatorTransfer.GetFieldDeserializers();
                }
                else if(Transfer != null)
                {
                    return Transfer.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(OriginatorTransfer != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.OriginatorTransfer>(null, OriginatorTransfer);
                }
                else if(Transfer != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Wise.OpenApiClient.Models.Transfer>(null, Transfer);
                }
            }
        }
    }
}
#pragma warning restore CS0618
