// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Profiles
{
    /// <summary>
    /// Business profile details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProfilesPostRequestBodyMember2_details : IAdditionalDataHolder, IParsable
    {
        /// <summary>Australian Business Number (only for Australian businesses).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Abn { get; set; }
#nullable restore
#else
        public string Abn { get; set; }
#endif
        /// <summary>Australian Company Number (only for Australian businesses).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Acn { get; set; }
#nullable restore
#else
        public string Acn { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Australian Registered Body Number (only for Australian businesses).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Arbn { get; set; }
#nullable restore
#else
        public string Arbn { get; set; }
#endif
        /// <summary>[Business category](/guides/developer/api-guides/business-categories).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessCategory { get; set; }
#nullable restore
#else
        public string BusinessCategory { get; set; }
#endif
        /// <summary>[Business sub-category](/guides/developer/api-guides/business-categories).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessSubCategory { get; set; }
#nullable restore
#else
        public string BusinessSubCategory { get; set; }
#endif
        /// <summary>Role of person.</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyRole? CompanyRole { get; set; }
        /// <summary>Company legal form.</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyType? CompanyType { get; set; }
        /// <summary>Sector / field of activity.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionOfBusiness { get; set; }
#nullable restore
#else
        public string DescriptionOfBusiness { get; set; }
#endif
        /// <summary>Business name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Business registration number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RegistrationNumber { get; set; }
#nullable restore
#else
        public string RegistrationNumber { get; set; }
#endif
        /// <summary>Business webpage. Required if companyType is OTHER.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Webpage { get; set; }
#nullable restore
#else
        public string Webpage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details"/> and sets the default values.
        /// </summary>
        public ProfilesPostRequestBodyMember2_details()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abn", n => { Abn = n.GetStringValue(); } },
                { "acn", n => { Acn = n.GetStringValue(); } },
                { "arbn", n => { Arbn = n.GetStringValue(); } },
                { "businessCategory", n => { BusinessCategory = n.GetStringValue(); } },
                { "businessSubCategory", n => { BusinessSubCategory = n.GetStringValue(); } },
                { "companyRole", n => { CompanyRole = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyRole>(); } },
                { "companyType", n => { CompanyType = n.GetEnumValue<global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyType>(); } },
                { "descriptionOfBusiness", n => { DescriptionOfBusiness = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "registrationNumber", n => { RegistrationNumber = n.GetStringValue(); } },
                { "webpage", n => { Webpage = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("abn", Abn);
            writer.WriteStringValue("acn", Acn);
            writer.WriteStringValue("arbn", Arbn);
            writer.WriteStringValue("businessCategory", BusinessCategory);
            writer.WriteStringValue("businessSubCategory", BusinessSubCategory);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyRole>("companyRole", CompanyRole);
            writer.WriteEnumValue<global::Soenneker.Wise.OpenApiClient.V1.Profiles.ProfilesPostRequestBodyMember2_details_companyType>("companyType", CompanyType);
            writer.WriteStringValue("descriptionOfBusiness", DescriptionOfBusiness);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("registrationNumber", RegistrationNumber);
            writer.WriteStringValue("webpage", Webpage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
