// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V1.Users.Exists;
using Soenneker.Wise.OpenApiClient.V1.Users.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Users
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\users
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UsersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The exists property</summary>
        public global::Soenneker.Wise.OpenApiClient.V1.Users.Exists.ExistsRequestBuilder Exists
        {
            get => new global::Soenneker.Wise.OpenApiClient.V1.Users.Exists.ExistsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Wise.OpenApiClient.v1.users.item collection</summary>
        /// <param name="position">The user ID.</param>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Users.Item.WithUserItemRequestBuilder"/></returns>
        public global::Soenneker.Wise.OpenApiClient.V1.Users.Item.WithUserItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::Soenneker.Wise.OpenApiClient.V1.Users.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/users", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Users.UsersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UsersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/users", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
