// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.KycReviews.Item.Requirements.Add
{
    /// <summary>The action to be carried out.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddPostRequestBody_requestedAction
    {
        [EnumMember(Value = "APPROVE")]
        #pragma warning disable CS1591
        APPROVE,
        #pragma warning restore CS1591
        [EnumMember(Value = "REJECT")]
        #pragma warning disable CS1591
        REJECT,
        #pragma warning restore CS1591
    }
}
