// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.KycReviews;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\simulation\profiles\{profileId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProfileItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The kycReviews property</summary>
        public global::Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.KycReviews.KycReviewsRequestBuilder KycReviews
        {
            get => new global::Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.KycReviews.KycReviewsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.WithProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProfileItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/simulation/profiles/{profileId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V2.Simulation.Profiles.Item.WithProfileItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProfileItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/simulation/profiles/{profileId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
