// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V1.Settlements
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SettlementsPostRequestBody_transfers : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Other data about the transfer or sender.For USA, you should send the account refund information for the sending customer (account number, routing number, street address, etc.)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>Name of the customer. Helps identify customer when manual operation is required.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerName { get; set; }
#nullable restore
#else
        public string CustomerName { get; set; }
#endif
        /// <summary>The date the transfer was created, ISO 8601 format.</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The exchange rate you used to calculate the settlement amount for this transfer.**Required if `settlementCurrency` is set on the journal.** You can set this value to be unique per transfer or the same for every transfer, depending on your settlement approach and agreements with Wise.</summary>
        public decimal? ExchangeRate { get; set; }
        /// <summary>ID of the transfer to be settled.</summary>
        public long? Id { get; set; }
        /// <summary>The transaction/payment identifier in your system, uniquely identifies the transfer in your platform.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartnerReference { get; set; }
#nullable restore
#else
        public string PartnerReference { get; set; }
#endif
        /// <summary>Transfer source amount with fee, always positive.</summary>
        public decimal? SourceAmount { get; set; }
        /// <summary>Transfer source currency (ISO 4217).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceCurrency { get; set; }
#nullable restore
#else
        public string SourceCurrency { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsPostRequestBody_transfers"/> and sets the default values.
        /// </summary>
        public SettlementsPostRequestBody_transfers()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsPostRequestBody_transfers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsPostRequestBody_transfers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V1.Settlements.SettlementsPostRequestBody_transfers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "customerName", n => { CustomerName = n.GetStringValue(); } },
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "exchangeRate", n => { ExchangeRate = n.GetDecimalValue(); } },
                { "id", n => { Id = n.GetLongValue(); } },
                { "partnerReference", n => { PartnerReference = n.GetStringValue(); } },
                { "sourceAmount", n => { SourceAmount = n.GetDecimalValue(); } },
                { "sourceCurrency", n => { SourceCurrency = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("customerName", CustomerName);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteDecimalValue("exchangeRate", ExchangeRate);
            writer.WriteLongValue("id", Id);
            writer.WriteStringValue("partnerReference", PartnerReference);
            writer.WriteDecimalValue("sourceAmount", SourceAmount);
            writer.WriteStringValue("sourceCurrency", SourceCurrency);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
