// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments
{
    [Obsolete("This class is obsolete. Use PaymentsPostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentsResponse : global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsPostResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Wise.OpenApiClient.V3.Profiles.Item.Transfers.Item.Payments.PaymentsResponse();
        }
    }
}
#pragma warning restore CS0618
